### ISSUE TITLE
v0.15 改造中 client 连没启动的 dispatcher 报错退出

### ISSUE THREAD

**Issue by kaven276** [noradle/noradle-dispatcher#6]
log from noradle-demo

```
  noradle:DBDriver socket end found! +5s
  noradle:DBDriver socket closed +0ms false
  noradle:DBDriver dispatcher closed +12ms
  noradle:DBDriver try connect to dispatcher +999ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

**Comment by kaven276** [comment]
原因可能是原先监听的时 net.socket.on(error|close|end) 现在改造成使用 http server 了，应该修正事件绑定到 http upgrade 后的 socket 上来。

`http.request({upgrade:'websocket...}).on('upgrade',...).on('error', retry_connect)`

如果 http.request(options) 连接不到 dispatcher，会 emit error，在此处定时重新尝试即可。
